export type Service = {
  slug: string;
  number: string;
  name: string;
  eyebrow: string;
  title: string;
  intro: string;
  items: string[];
  focusTitle: string;
  focus: string;
  image: "sea" | "air" | "land";
};

export const services: Service[] = [
  { slug: "sea-freight", number: "01", name: "Sea Freight", eyebrow: "FCL · LCL · Global ports", title: "Global Trade, Powered by Ocean Logistics", intro: "Ocean freight remains the backbone of international trade. We help businesses move cargo across international markets with coordinated sea freight solutions planned around cargo type, destination, volume, timeline and budget.", items: ["Full Container Load — FCL", "Less than Container Load — LCL", "Export & import shipments", "Port-to-port services", "Door-to-port solutions", "Port-to-door solutions", "Container coordination", "Documentation support", "Carrier coordination", "Shipment planning", "Destination handling"], focusTitle: "Smart routes. Coordinated carriers.", focus: "From booking and documentation to destination coordination, we identify practical routes that balance transit time and cost.", image: "sea" },
  { slug: "air-freight", number: "02", name: "Air Freight", eyebrow: "Urgent · High-value · Time-critical", title: "When Every Hour Counts, Move by Air", intro: "For urgent, high-value and time-sensitive cargo, air freight offers speed and reliability. Our coordinated solutions help businesses meet demanding delivery schedules without compromising shipment visibility and support.", items: ["Import air freight", "Export air freight", "Airport-to-airport", "Door-to-door", "Express cargo", "Time-critical shipments", "High-value cargo", "Documentation support", "Customs coordination"], focusTitle: "Built for time-sensitive cargo.", focus: "We select suitable routing and handling options based on urgency, cargo characteristics and destination. Fast decisions. Coordinated execution. Reliable delivery.", image: "air" },
  { slug: "land-freight", number: "03", name: "Land Freight", eyebrow: "First mile · Final mile · Distribution", title: "Connecting Ports, Plants, Warehouses & Markets", intro: "Efficient land transportation is the link that completes your supply chain. We coordinate dependable road movement between factories, warehouses, ports, distribution centres and final destinations.", items: ["Container transportation", "Full Truck Load", "Part Truck Load", "First-mile transportation", "Last-mile delivery", "Port pickup & delivery", "Factory pickup", "Warehouse transfers", "Domestic cargo movement", "Distribution support"], focusTitle: "Right vehicle. Right route. Right time.", focus: "Transportation is coordinated according to cargo requirements, location, delivery schedule and operational needs.", image: "land" },
  { slug: "cross-trade", number: "04", name: "Cross Trade", eyebrow: "Supplier · Buyer · International freight", title: "Global Trade Without Geographic Limitations", intro: "Your buyer may be in one country, your supplier in another, and your business somewhere else. We coordinate international shipments between two countries without requiring cargo to pass through your home country.", items: ["Supplier coordination", "Buyer coordination", "International freight", "Documentation", "Shipping coordination", "Shipment monitoring", "Destination coordination", "Stakeholder communication"], focusTitle: "Simplify multi-country trade.", focus: "We bring suppliers, buyers, carriers and logistics partners into one coordinated shipment process. More flexibility. Fewer complications.", image: "sea" },
  { slug: "customs-clearance", number: "05", name: "Customs Clearance", eyebrow: "Import · Export · Compliance", title: "Making Border Compliance Simpler", intro: "Customs procedures become complex when documentation, regulations and shipment timelines converge. Our support helps businesses navigate import and export requirements with better coordination and documentation management.", items: ["Import customs clearance", "Export customs clearance", "Documentation coordination", "Shipment documentation", "Customs process coordination", "Port & terminal coordination", "Regulatory support", "Duty & tax coordination"], focusTitle: "Reduce delays. Improve coordination.", focus: "We organize the moving pieces around border compliance to help keep your cargo moving.", image: "sea" },
  { slug: "warehousing", number: "06", name: "Warehousing", eyebrow: "Storage · Consolidation · Distribution", title: "More Than Storage. A Smarter Supply-Chain Link", intro: "Warehousing is an important part of the logistics journey. RVR provides support designed around storage, handling, consolidation and distribution requirements.", items: ["Short-term storage", "Long-term storage", "Cargo consolidation", "Deconsolidation", "Loading & unloading", "Inventory handling", "Distribution support", "Cargo handling", "Dispatch coordination"], focusTitle: "Secure. Organized. Accessible.", focus: "Our objective is to ensure cargo remains properly managed while waiting for its next destination.", image: "land" },
  { slug: "project-cargo", number: "07", name: "Project Cargo & Handling", eyebrow: "Heavy · Oversized · Specialized", title: "When Cargo Is Complex, Planning Makes the Difference", intro: "Oversized, heavy, high-value and specialized cargo requires more than conventional transportation. We coordinate project movements around dimensions, weight, handling, routing and delivery requirements.", items: ["Heavy cargo", "Oversized cargo", "Machinery", "Industrial equipment", "Plant & project materials", "Specialized handling", "Route planning", "Loading & unloading", "Transportation coordination", "Delivery planning"], focusTitle: "Every dimension matters.", focus: "We take a planning-first approach because complex cargo leaves little room for error.", image: "land" },
  { slug: "door-to-door", number: "08", name: "Door-to-Door Logistics", eyebrow: "Pickup · Freight · Final delivery", title: "One Journey. From Pickup to Final Delivery", intro: "Why coordinate multiple providers when one partner can manage the journey? Our door-to-door solution brings together pickup, transportation, freight forwarding, customs, handling and final delivery.", items: ["Supplier or factory pickup", "First-mile transportation", "Freight transportation", "Customs & documentation", "Destination handling", "Final delivery"], focusTitle: "One point of coordination.", focus: "We manage the logistics journey so you can focus on your business.", image: "land" },
  { slug: "cargo-inspection", number: "09", name: "Cargo Inspection", eyebrow: "Inspect · Verify · Ship", title: "Confidence Before Your Cargo Moves", intro: "Cargo inspection gives businesses greater visibility into the condition, quantity and specifications of goods before shipment. RVR coordinates inspection support according to shipment requirements.", items: ["Pre-shipment inspection", "Quantity verification", "Quality checks", "Cargo condition", "Loading supervision", "Packaging verification", "Documentation verification", "Photo & report coordination"], focusTitle: "Ship with confidence.", focus: "Better information before dispatch can mean fewer surprises later.", image: "sea" },
];

export const industries = ["Industrial Products", "Engineering Goods", "Chemicals", "Minerals", "Metals", "Ceramic & Tiles", "Agricultural Products", "Food & FMCG", "Machinery & Equipment", "Automotive Components", "Textiles & Garments", "Consumer Products", "Project Cargo", "General Cargo"];

export const getService = (slug: string) => services.find((service) => service.slug === slug);